#files = ["A", "B", "C"]
mynumbers = [1, 2]

rule combine:
#	input: expand("input1/{file}.txt", file = files)
#	input: "input/A.txt", "input/B.txt", "input/C.txt"
	input: "input{number}/"
	output: "combined{number}.txt"
	shell:
		"""
		cat {input}/*.txt >> {output}
		"""

rule lower:
	input: rules.combine.output
	output: "lower{number}.txt"
	threads: 2
	shell:
		"""
		cat {input} | tr [:upper:] [:lower:] > {output}
		"""
rule all:
	input: expand("lower{number}.txt", number=mynumbers)
